#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -d dummy-payment-app ]]; then
  echo "dummy-payment-app/ not found. Run: npm run setup"
  exit 1
fi

PORT="${DUMMY_PAYMENT_APP_PORT:-3001}"
IFRAME_URL="${DUMMY_PAYMENT_APP_IFRAME_URL:-http://localhost:${PORT}}"
API_URL="${DUMMY_PAYMENT_APP_API_URL:-http://host.docker.internal:${PORT}}"

ENV_FILE="dummy-payment-app/.env"

cat > "$ENV_FILE" <<EOF
# Generated by saleor-e2e (scripts/configure-dummy-payment-app.sh)
APP_IFRAME_BASE_URL=${IFRAME_URL}
APP_API_BASE_URL=${API_URL}
APL=file
FILE_APL_PATH=${ROOT}/dummy-payment-app/.saleor-app-auth.json
PORT=${PORT}
EOF

echo "Configured dummy-payment-app/.env (port ${PORT}, API URL for Docker: ${API_URL})"
